users:
  admin2@gmail.com:
    password: $2b$12$hrfxiGbteAMCH9i34op.MO6NEAwDsmKSYujOFDusyiCHepMktCVjS
    role: admin
  gen1@gmail.com:
    password: $2b$12$633vn/JjNdJt2.avdzY2leABnhF3.sCvXLm8To1xjMcss7a2v5XOW
    role: user
  xyz@gmail.com:
    password: xyz123
    role: user
